name: Generate HTML files for RSS items

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        run: |
          go build -o main.go

      - name: Add execute permission to main
        run: chmod +x ./main    

      - name: Run
        run: |
          ./main

      - name: Commit Changes
        run: |
          git config --global user.name "zxjack"
          git config --global user.email "zxjack@gmail.com"
          git add rss-stared/*
          git commit -m "Update RSS articles"
        
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          branch: master
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}    
        