name: Generate HTML files for RSS items

on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        run: |
          go build -o main main.go

      - name: Add execute permission to main
        run: chmod +x ./main

      - name: Run
        run: |
          ./main

env:
  GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION=true
