name: Generate HTML files for RSS items

on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install dependencies
        run: |
          go get -v -t -d ./...

      - name: Fix oauth2.go build issue
        run: |
         go mod download golang.org/x/oauth2
         echo "GOPATH: $GOPATH"
         echo "go mod cache: $(go env GOMODCACHE)"
         cd /home/runner/go/pkg/mod/golang.org/x/oauth2@v0.0.0-20210819172956-2ccce9b4a323
         sed -i '1s/^/\/\/ +build !js\n\n/' oauth2.go

      - name: Build
        run: |
          go build -o main main.go

      - name: Add execute permission to main
        run: chmod +x ./main

      - name: Run
        run: |
          ./main

env:
  GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

